name: dslink_mongodb
description: MongoDB for DSA
dependencies:
  dslink:
    git: https://github.com/IOT-DSA/sdk-dslink-dart.git
  mongo_dart: "^0.2.5+1"
  package_config: "^0.1.3"
  connection_pool: "^0.1.0+2"
  stack_trace: "^1.6.1"
  logging: any

